%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.13.0

-ifndef(game_11_pb).
-define(game_11_pb, true).

-define(game_11_pb_gpb_version, "4.13.0").

-ifndef('GAME_S_ERROR_PB_H').
-define('GAME_S_ERROR_PB_H', true).
-record(game_s_error,
        {proto = 0              :: non_neg_integer() | undefined, % = 1, 32 bits
         code = 0               :: non_neg_integer() | undefined % = 2, 32 bits
        }).
-endif.

-endif.
