%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.13.0

-ifndef(battle_14_pb).
-define(battle_14_pb, true).

-define(battle_14_pb_gpb_version, "4.13.0").


-endif.
