%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.13.0

-ifndef(gateway_12_pb).
-define(gateway_12_pb, true).

-define(gateway_12_pb_gpb_version, "4.13.0").

-ifndef('GATEWAY_C_LOGIN_PB_H').
-define('GATEWAY_C_LOGIN_PB_H', true).
-record(gateway_c_login,
        {account = <<>>         :: iodata() | undefined % = 1
        }).
-endif.

-ifndef('GATEWAY_P_ROLE_INFO_PB_H').
-define('GATEWAY_P_ROLE_INFO_PB_H', true).
-record(gateway_p_role_info,
        {id = 0                 :: non_neg_integer() | undefined, % = 1, 32 bits
         name = <<>>            :: iodata() | undefined % = 2
        }).
-endif.

-ifndef('GATEWAY_S_LOGIN_PB_H').
-define('GATEWAY_S_LOGIN_PB_H', true).
-record(gateway_s_login,
        {account = <<>>         :: iodata() | undefined, % = 1
         role_list = []         :: [gateway_12_pb:gateway_p_role_info()] | undefined % = 2
        }).
-endif.

-ifndef('GATEWAY_C_SELECT_ROLE_PB_H').
-define('GATEWAY_C_SELECT_ROLE_PB_H', true).
-record(gateway_c_select_role,
        {id = 0                 :: non_neg_integer() | undefined % = 1, 32 bits
        }).
-endif.

-ifndef('GATEWAY_S_SELECT_ROLE_PB_H').
-define('GATEWAY_S_SELECT_ROLE_PB_H', true).
-record(gateway_s_select_role,
        {id = 0                 :: non_neg_integer() | undefined % = 1, 32 bits
        }).
-endif.

-ifndef('GATEWAY_C_CREATE_ROLE_PB_H').
-define('GATEWAY_C_CREATE_ROLE_PB_H', true).
-record(gateway_c_create_role,
        {name = <<>>            :: iodata() | undefined % = 1
        }).
-endif.

-ifndef('GATEWAY_S_CREATE_ROLE_PB_H').
-define('GATEWAY_S_CREATE_ROLE_PB_H', true).
-record(gateway_s_create_role,
        {role_list = []         :: [gateway_12_pb:gateway_p_role_info()] | undefined % = 1
        }).
-endif.

-ifndef('GATEWAY_C_HEART_PB_H').
-define('GATEWAY_C_HEART_PB_H', true).
-record(gateway_c_heart,
        {
        }).
-endif.

-ifndef('GATEWAY_S_HEART_PB_H').
-define('GATEWAY_S_HEART_PB_H', true).
-record(gateway_s_heart,
        {
        }).
-endif.

-endif.
