%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.13.0

-ifndef(player_13_pb).
-define(player_13_pb, true).

-define(player_13_pb_gpb_version, "4.13.0").

-ifndef('PLAYER_C_INFO_PB_H').
-define('PLAYER_C_INFO_PB_H', true).
-record(player_c_info,
        {
        }).
-endif.

-ifndef('PLAYER_S_INFO_PB_H').
-define('PLAYER_S_INFO_PB_H', true).
-record(player_s_info,
        {id = 0                 :: non_neg_integer() | undefined, % = 1, 32 bits
         name = <<>>            :: iodata() | undefined % = 2
        }).
-endif.

-endif.
